#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["CodeTest.Tests/CodeTest.Tests.csproj", "CodeTest.Tests/"]
COPY ["NumberSeries/NumberSeries.csproj", "NumberSeries/"]
RUN dotnet restore "CodeTest.Tests/CodeTest.Tests.csproj"
RUN dotnet test "CodeTest.Tests/CodeTest.Tests.csproj"
COPY . .
WORKDIR "/src/CodeTest.Tests"
RUN dotnet build "CodeTest.Tests.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet test CodeTest.Tests.csproj -c Release
RUN dotnet publish "CodeTest.Tests.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CodeTest.Tests.dll"]
