name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./src/CodeTest.Tests
      run: dotnet restore
    - name: Build
      working-directory: ./src/CodeTest.Tests
      run: dotnet build --no-restore
    - name: Run Tests
      working-directory: ./src/CodeTest.Tests
      run: dotnet test --no-build --verbosity normal
